### ISSUE TITLE
Add more references from zenodo

### ISSUE THREAD

**Issue by omarcostahamido** [isqcmc/isqcmc.github.io#9]
@Itaborala on our website we have the fancy bibtex, and on zenodo we have everything else. But you need to know that in order to find it. 
Could we add some info somewhere that clarifies that?

(Of course the overcomplicated solution would be to parse the web pages and include all those ref styles on our website...)

**TODO:**
- [x] Add dropdown with all the options being first one BibTeX, and an additional button for copy to clipboard
- [x] create additional javascript dictionaries for all other citation styles.

**Comment by omarcostahamido** [comment]
- [ ] Add dropdown with all the options being first one BibTeX, and an additional button for copy to clipboard
- [ ] create additional javascript dictionaries for all other citation styles.

**Comment by omarcostahamido** [comment]
changes ready to receive dictionaries in https://github.com/isqcmc/isqcmc.github.io/tree/newbuttons
@Itaborala

**Comment by omarcostahamido** [comment]
just need these dicts to exist:
https://github.com/isqcmc/isqcmc.github.io/blob/d4419094723f07ed1530c39b7ad3a74679377a0d/_layouts/default.html#L20-L32

**Comment by Itaborala** [comment]
The dicts now exist since https://github.com/isqcmc/isqcmc.github.io/commit/f87b2e8cbed173cfb38d0768e208fe4d19e94ca2.

I will be filling them on my way back

**Comment by omarcostahamido** [comment]
not gonna lie, I thought about doing it programmatically, as in retrieving automatically from zenodo, but I will let you take your points on the issue however you prefer ;) 
(I was looking into zenodo a bit and it seems they just have a dictionary of sorts whose entries they pull from to construct the citations. pretty clever tbh, haven't found the code that does the assembly though)

**Comment by omarcostahamido** [comment]
They can also all be on the same file but just different dictionaries. it would imply renaming the current one, only.

**Comment by Itaborala** [comment]
Ok, I will gather them in a single dictionary

**Comment by omarcostahamido** [comment]
maybe not a single dictionary: a single file, with the multiple dictionaries. No?

**Comment by Itaborala** [comment]
Correct, that's what I meant :)

**Comment by Itaborala** [comment]
Please check if it works

**Comment by omarcostahamido** [comment]
Thx. Just one question: on IEEE the [1] is glued to the start of the
author's name. Is that by design?

**Comment by omarcostahamido** [comment]
it's perfect. I'll merge. I tried to get the copy icon on each option, but it doesn't show up on the mac. not totally satisfies with the visual, but I think it is pretty good.
